apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nginx-demo-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: nginx-demo
  destination:
    name: nginx-demo-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth